dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
            - libprotobuf-dev
            - libopencv-dev
            - libprotoc-dev
            - protobuf-compiler
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - cd "$HOME"
    - .travis/install_protoc
    - .travis/install_mkldnn
script:
    - cd "$HOME/instant"
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./example/vgg16_example
