dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - git clone https://github.com/01org/mkl-dnn.git
    - cd mkl-dnn/scripts && bash ./prepare_mkl.sh && cd ..
    - grep -v "add_subdirectory(examples)" > CMakkeLists.txt
    - grep -v "add_subdirectory(tests)" > CMakkeLists.txt
    - mkdir -p build && cd build && cmake .. && make
    - sudo make install
    - cd ..
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./example/vgg16_example
