dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
            - libprotobuf-dev
            - libopencv-dev
            - libprotoc-dev
            - protobuf-compiler
cache:
    directories:
        - $HOME/protobuf
        - $HOME/mkl-dnn
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - cd "$HOME"
    - sh "$HOME/.travis/install_protoc.sh"
    - sh "$HOME/.travis/install_mkldnn.sh"
script:
    - cd "$HOME/instant"
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./example/vgg16_example
