dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
            - libopencv-dev
cache:
    directories:
        - $HOME/protoc
        - $HOME/mkl-dnn
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - sh .travis/install_protoc.sh
    - sh .travis/install_mkldnn.sh
before_script:
    - ls -R $HOME/protoc
    - ls -R $HOME/mkl-dnn
script:
    - mkdir build
    - cd build
    - cmake -DPROTOC="$HOME/protoc/bin/protoc" -DPROTOBUF_INCLUDE_DIR="$HOME/protoc/include" -DPROTOBUF_LIBRARY="$HOME/protoc/lib/libprotobuf.so" -DPROTOBUF_PROTOC_LIBRARY="$HOME/protoc/lib/libprotoc.so" ..
    - make
    - ./example/vgg16_example
