dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-7
            - g++-7
            - cmake-data
            - cmake
            - libopencv-dev
cache:
    directories:
        - $HOME/protoc
        - $HOME/mkl-dnn
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - sh .travis/install_protoc.sh
    - sh .travis/install_mkldnn.sh
    - sh retrieve_data.sh
before_script:
    - ls -R $HOME/protoc
    - ls -R $HOME/mkl-dnn
script:
    - mkdir build
    - cd build
    - sh ../.travis/run_cmake.sh
    - make
    - ./test/instant_test
