dist: trusty
sudo: required
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
            - libprotobuf-dev
            - libopencv-dev
            - libprotoc-dev
            - protobuf-compiler
cache:
    directories:
        - $HOME/protoc
        - $HOME/mkl-dnn
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - sh .travis/install_protoc.sh
    - sh .travis/install_mkldnn.sh
script:
    - mkdir build
    - cd build
    - cmake -DPROTOC="$HOME/protobuf/src/protoc" ..
    - make
    - ./example/vgg16_example
